apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd
spec:
  host: argocd.apps.origin.baloise.dev
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: argocd-server
    weight: 100
status:
  ingress:
    - routerName: router

