apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
spec:
  refreshInterval: 1h0m0s
  refreshPolicy: CreatedOnce
  target:
    name: argo-workflows-sso
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        client-id: argo-workflows-sso
        client-secret: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: argo-workflows-sso
