apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  type: ClusterIP
