apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 128M
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 128M
  ee_resource_requirements:
    requests:
      cpu: 200m
      memory: 64M
  ingress_type: route
  route_host: awx.apps.baloise.dev
  route_tls_termination_mechanism: Edge