apiVersion: cache.jhouse.com/v1alpha1
kind: NFSProvisioner
metadata:
  name: nfsprovisioner
  namespace: nfs-provisioner
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  scForNFS: nfs
  scForNFSPvc: lvms-vg1
  storageSize: 100G
