apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: kubernetes-argocd
  target:
    name: argo-workflows-sso
  data:
    - secretKey: client-id
      remoteRef:
        key: argo-workflows-sso
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: argo-workflows-sso
        property: client-secret
