apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: litellm-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: openai-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/openai-api-key
    - secretKey: azure-openai-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/azure-openai-api-key
    - secretKey: azure-openai-api-base
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/azure-openai-api-base
    - secretKey: azure-openai-api-version
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/azure-openai-api-version
    - secretKey: anthropic-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/anthropic-api-key
    - secretKey: master-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/master-key
    - secretKey: postgres-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/litellm/postgres-password
