apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: litellm-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: azure-foundry-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /baloise-incubator/cluster-infra/litellm/azure-foundry-api-key
    - secretKey: azure-foundry-router-api-base
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /baloise-incubator/cluster-infra/litellm/azure-foundry-router-api-base
    - secretKey: azure-foundry-anthropic-api-base
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /baloise-incubator/cluster-infra/litellm/azure-foundry-anthropic-api-base
    - secretKey: azure-foundry-openai-api-base
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /baloise-incubator/cluster-infra/litellm/azure-foundry-openai-api-base
    - secretKey: master-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /baloise-incubator/cluster-infra/litellm/master-key
    - secretKey: postgres-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /baloise-incubator/cluster-infra/litellm/postgres-password
