apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-server-provisioner

helmCharts:
  - name: nfs-server-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
    version: 1.8.0
    releaseName: nfs-server-provisioner
    namespace: nfs-server-provisioner
    valuesInline:
      persistence:
        enabled: true
        storageClass: lvms-vg1
        size: 1Ti
      storageClass:
        name: nfs
        defaultClass: false
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        mountOptions:
          - vers=4.1
          - noatime
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi

resources:
  - scc.yaml
