apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-dispatch-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-dispatch
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-dispatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-dispatch
subjects:
  - kind: ServiceAccount
    name: argo-dispatch-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-executor
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-executor
subjects:
  - kind: ServiceAccount
    name: argo-dispatch-sa
