apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-recipes
data:
  {{- range $path, $content := .Files.Glob "recipes/*.yaml" }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}
  {{- end }}
