apiVersion: v1
kind: Service
metadata:
  name: argo-dispatch
spec:
  selector:
    app: argo-dispatch
  ports:
    - name: http
      port: {{ .Values.argoDispatch.port }}
      targetPort: http
      protocol: TCP
  type: ClusterIP
