apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: workstation
spec:
  running: true
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.xlarge
  preference:
    kind: VirtualMachineClusterPreference
    name: fedora
  dataVolumeTemplates:
    - metadata:
        name: workstation-rootdisk
      spec:
        source:
          registry:
            url: docker://quay.io/containerdisks/fedora:latest
            pullMethod: node
        storage:
          accessModes:
            - ReadWriteOnce
          volumeMode: Filesystem
          resources:
            requests:
              storage: 100Gi
          storageClassName: nfs
  template:
    metadata:
      labels:
        app: workstation
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: workstation-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              runcmd:
                - curl -fsSL https://code-server.dev/install.sh | sh
                - mkdir -p /root/.config/code-server
                - |
                  cat > /root/.config/code-server/config.yaml <<EOF
                  bind-addr: 0.0.0.0:8080
                  auth: none
                  cert: false
                  EOF
                - systemctl enable --now code-server@root
