apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  template:
    spec:
      containers:
        - name: minio-operator
          securityContext:
            $patch: delete
