apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/external-secret.yaml
  - base/eventbus.yaml
  - base/eventsource.yaml
  - base/sensor.yaml
  - base/workflow-template.yaml
  - base/route.yaml
  - base/dnsendpoint.yaml
  - base/rbac.yaml
