apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v3.1.0
  - base/argocd-ui-route.yaml
  - base/dnsendpoint.yaml
  - base/default-appprojects.yaml
  - base/servicemonitors.yaml
  - base/bootstrap-application.yaml
  - base/dex-sa-token-secret.yaml

patchesStrategicMerge:
  - overlays/catalog-install.yaml
  - overlays/argocd-application-controller.yaml
  - overlays/argocd-cm.yaml
  - overlays/argocd-dex-server.yaml
  - overlays/argocd-dex-server-sa.yaml
  - overlays/argocd-rbac-cm.yaml
  - overlays/argocd-redis.yaml
  - overlays/argocd-redis-ha-haproxy.yaml
  - overlays/argocd-server-deploy.yaml
  - overlays/argocd-repo-server-deploy.yaml
  - overlays/argocd-notifications-cm.yaml
  - overlays/networkpolicies.yaml
