apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook
spec:
  eventBusName: default
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    default:
      organizations:
        - baloise-incubator
      active: false
      contentType: json
      webhook:
        endpoint: /github
        method: POST
        port: "12000"
        url: https://gitopscli-webhook.baloise.dev
      webhookSecret:
        name: github-token
        key: webhook-secret
      events:
        - push
      insecure: false
