apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /baloise-incubator/github/token
        metadataPolicy: None
      secretKey: token
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /baloise-incubator/github/webhook-secret
        metadataPolicy: None
      secretKey: webhook-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
