apiVersion: v1
kind: ConfigMap
metadata:
  name: openhands-config
data:
  config.toml: |
    [core]
    workspace_base = "/opt/workspace"
    enable_browser = false

    [sandbox]
    runtime_container_image = "ghcr.io/all-hands-ai/runtime:oh_v0.59.0_image_nikolaik_s_python-nodejs_tag_python3.12-nodejs22"

    [llm]
    model = "claude-sonnet-4-6"
    base_url = "https://litellm.baloise.dev"
    drop_params = true
