apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openhands-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: openhands-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: litellm-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/openhands/litellm-api-key
    - secretKey: github-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /github/token
