apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudinit-secret.yaml
  - configmap.yaml
  - vm.yaml
  - service.yaml
  - external-secret.yaml
  - oauth-proxy.yaml
  - route.yaml
  - dnsendpoint.yaml
  - rbac.yaml
