apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: openhands
spec:
  running: true
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.xlarge
  preference:
    kind: VirtualMachineClusterPreference
    name: fedora
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: openhands-rootdisk
      spec:
        source:
          registry:
            url: docker://quay.io/containerdisks/fedora:latest
            pullMethod: node
        storage:
          accessModes:
            - ReadWriteOnce
          volumeMode: Filesystem
          resources:
            requests:
              storage: 100Gi
          storageClassName: lvms-vg1
  template:
    metadata:
      labels:
        app: openhands
    spec:
      nodeSelector:
        kubernetes.io/hostname: masterp001.baloise.dev
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 22
                - port: 3000
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: secrets
              disk:
                bus: virtio
            - name: config
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: openhands-rootdisk
        - name: secrets
          secret:
            secretName: openhands-secrets
            volumeLabel: secrets
        - name: config
          configMap:
            name: openhands-config
            volumeLabel: config
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: openhands-cloudinit
