apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: dex-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: librechat-client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/dex-librechat-client-secret
