apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: librechat-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: mongodb-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/mongodb-password
    - secretKey: litellm-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/agent-platform/litellm-api-key
    - secretKey: litellm-model
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/agent-platform/litellm-model
    - secretKey: oidc-client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/dex-librechat-client-secret
    - secretKey: creds-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/creds-key
    - secretKey: creds-iv
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/creds-iv
    - secretKey: jwt-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/jwt-secret
    - secretKey: jwt-refresh-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /cluster-infra/librechat/jwt-refresh-secret
