apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: jenkins
spec:
  endpoints:
    - dnsName: {{ .Values.controller.route.path }}
      recordType: A
      targets: [""]